import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/images/courses/a9e7b27a0c5e986a22416d79e2e9dba9.jpg',
    title: 'Cybersecurity and Risk Management',
    rating: 5,
    duration: '6 Months',
    ratingCount: 8,
    category: 'Beginner',
  },
  {
    id: 2,
    cover: '/images/courses/cyber.jpg',
    title: 'Cyber Warfare',
    rating: 5,
    duration: '2 Months',
    ratingCount: 15,
    category: 'Intermediate',
  },
  {
    id: 3,
    cover: '/images/courses/christopher-gower-m_HRfLhgABo-unsplash.jpg',
    title: 'Enterprise Cybersecurity Management or GRC',
    rating: 4,
    duration: '2 Months',
    ratingCount: 7,
    category: 'Beginner',
  },
  {
    id: 4,
    cover: '/images/courses/image4.jpg',
    title: 'Investigating Online Crime',
    rating: 4,
    duration: '4 Months',
    ratingCount: 12,
    category: 'Intermediate',
  },
  {
    id: 5,
    cover: '/images/courses/image5.jpg',
    title: 'Offensive Cyber Security',
    rating: 4,
    duration: '2 Months',
    ratingCount: 32,
    category: 'Intermediate',
  },
  {
    id: 6,
    cover: '/images/courses/risk.jpg',
    title: 'Third-Party Risk Management',
    rating: 5,
    duration: '2 Months',
    ratingCount: 14,
    category: 'Beginner',
  },
  {
    id: 6,
    cover: '/images/courses/img8.jpg',
    title: 'Cloud Security Professional',
    rating: 5,
    duration: '3 Months',
    ratingCount: 14,
    category: 'Beginner',
  },
]
